# Generated by Django 3.1 on 2020-09-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auteur', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('contenu', models.TextField(max_length=200, null=True)),
                ('image', models.ImageField(null=True, upload_to=None)),
                ('data_creates', models.DateTimeField(auto_now_add=True, null=True)),
                ('domain', models.CharField(choices=[('websites', 'websites'), ('apps', 'apps'), ('haking', 'haking'), ('articales', 'articales')], max_length=200, null=True)),
            ],
        ),
    ]
