# Generated by Django 3.1 on 2020-09-28 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200928_1516'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='domain',
        ),
    ]
